### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [wolfbolin/DNSPodX#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary dnspodx -w /tmp/ext dnspodx==0.0.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting dnspodx==0.0.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/6a1/4cfeea3daa6c9/DNSPodX-0.0.1.tar.gz (6.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ypjpxtlf/dnspodx/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ypjpxtlf/dnspodx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ypjpxtlf/dnspodx/pip-egg-info
         cwd: /tmp/pip-wheel-ypjpxtlf/dnspodx/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ypjpxtlf/dnspodx/setup.py", line 52, in <module>
        with open(os.path.join(here, project_slug, '__version__.py')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ypjpxtlf/dnspodx/dnspodx/__version__.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by wolfbolin** [comment]
Try to use `pip install—upgrade pip` or `pip install --upgrade setuptools` to update your pip and setuptools

**Comment by thatch** [comment]
My setuptools is 44.x, and I'm pretty sure this is your sdist missing files.  I tried to fix it for you but this repo doesn't have the setup.py or anything else that would let me package it.  Can you help me understand where the setup.py in dnspodx==0.0.1 came from?
